### ISSUE TITLE
Unable to see the titlebar and sidebar files text

### ISSUE THREAD

**Issue by f-x1-1** [rkstrdee/night-hacker-dark-theme#1]
![sdfcsd](https://user-images.githubusercontent.com/77340515/116884520-588fa900-ac16-11eb-96c3-9585e00dc14f.png)

I'm facing this issue everytime i select this theme.

**Comment by ddh4r4m** [comment]
This issue has been resolved in the latest update, update your extension. Happy Coding!!😎

**Comment by f-x1-1** [comment]
Thank you!
