### ISSUE TITLE
unable to view my code error in terminal becoz of color, i tried to change but it is not working , i'm coding in js 

### ISSUE THREAD

**Issue by Indratejreddy** [rkstrdee/night-hacker-dark-theme#2]
![pol](https://user-images.githubusercontent.com/66834653/117493293-6afc4080-af90-11eb-8273-ab21471c38fb.PNG)

**Comment by ddh4r4m** [comment]
Issue resolved!! ⌨️

**Comment by Indratejreddy** [comment]
i want that green color like u guys show in theme

**Comment by Indratejreddy** [comment]
![8](https://user-images.githubusercontent.com/66834653/117864038-03a50000-b2b2-11eb-9ddd-f8edae5c75cc.PNG)
how can i get the green color like i have in side bars for my terminal , that blue color look ugly

**Comment by ddh4r4m** [comment]
You can add this line in your "settings.json" 
`"workbench.colorCustomizations": {
        "terminal.foreground": "#33ff00"
      }
`
to get the desired color of your choice.
if you want more tweaking, the code provided below can be helpful.
`"workbench.colorCustomizations": {
        "terminal.foreground": "#00ffea",
      "terminal.ansiBlack": "#060016",
      "terminal.ansiBlue": "#071399",
      "terminal.ansiBrightBlack": "#ff1e00",
      "terminal.ansiBrightBlue": "#5ca9fa",
      "terminal.ansiBrightCyan": "#3EFF70",
      "terminal.ansiBrightGreen": "#46df46",
      "terminal.ansiBrightMagenta": "#d606cf",
      "terminal.ansiBrightRed": "#f02727",
      "terminal.ansiBrightWhite": "#ffffff",
      "terminal.ansiBrightYellow": "#fffb00",
      "terminal.ansiCyan": "#3EFF70",
      "terminal.ansiGreen": "#0aed43",
      "terminal.ansiMagenta": "#06D6A0",
      "terminal.ansiRed": "#ff0000",
      "terminal.ansiWhite": "#ffffff",
      "terminal.ansiYellow": "#d0ff00",
      "terminalCursor.background": "#060016",
      "terminalCursor.foreground": "#06D6A0",
      }
      `
